import {
    SULBP1, SULBP2, SULBP3, SULBP4,
    GYTEP1, GYTEP2, GYTEP3, GYTEP4,
    POTTERP1, POTTERP2, POTTERP3, POTTERP4,
    POWERSP1, POWERSP2, POWERSP3, POWERSP4,
    CLOP1, CLOP2, CLOP3, CLOP4,
    ANDERSONP1, ANDERSONP2, ANDERSONP3, ANDERSONP4,
    NILSP1, NILSP2, NILSP3, NILSP4, 
    PORTERP1, PORTERP2, PORTERP3, PORTERP4,
    OFFICEP1, OFFICEP2, OFFICEP3, OFFICEP4,
    FITNESSP1, FITNESSP2, FITNESSP3, FITNESSP4,
    COUNSELINGP1, COUNSELINGP2, COUNSELINGP3, COUNSELINGP4
} from "./location";

export const buildingPoints = {
    SULB: [SULBP1, SULBP2, SULBP3, SULBP4],
    GYTE: [GYTEP1, GYTEP2, GYTEP3, GYTEP4],
    POTTER: [POTTERP1, POTTERP2, POTTERP3, POTTERP4],
    POWERS: [POWERSP1, POWERSP2, POWERSP3, POWERSP4],
    CLO: [CLOP1, CLOP2, CLOP3, CLOP4],
    ANDERSON: [ANDERSONP1, ANDERSONP2, ANDERSONP3, ANDERSONP4],
    NILS: [NILSP1, NILSP2, NILSP3, NILSP4],
    PORTER: [PORTERP1, PORTERP2, PORTERP3, PORTERP4],
    OFFICE: [OFFICEP1, OFFICEP2, OFFICEP3, OFFICEP4],
    FITNESS: [FITNESSP1, FITNESSP2, FITNESSP3, FITNESSP4],
    COUNSELING: [COUNSELINGP1, COUNSELINGP2, COUNSELINGP3, COUNSELINGP4]
};