import {
    SULBP1, SULBP2, SULBP3,
    GYTEP1, GYTEP2, GYTEP3,
    POTTERP1, POTTERP2, POTTERP3,
    POWERSP1, POWERSP2, POWERSP3,
    CLOP1, CLOP2, CLOP3,
    ANDERSONP1, ANDERSONP2, ANDERSONP3,
    NILSP1, NILSP2, NILSP3,
    PORTERP1, PORTERP2, PORTERP3,
    OFFICEP1, OFFICEP2, OFFICEP3,
    FITNESSP1, FITNESSP2, FITNESSP3,
    COUNSELINGP1, COUNSELINGP2, COUNSELINGP3
} from "./location";

export const buildingPoints = {
    SULB: [SULBP1, SULBP2, SULBP3],
    GYTE: [GYTEP1, GYTEP2, GYTEP3],
    POTTER: [POTTERP1, POTTERP2, POTTERP3],
    POWERS: [POWERSP1, POWERSP2, POWERSP3],
    CLO: [CLOP1, CLOP2, CLOP3],
    ANDERSON: [ANDERSONP1, ANDERSONP2, ANDERSONP3],
    NILS: [NILSP1, NILSP2, NILSP3],
    PORTER: [PORTERP1, PORTERP2, PORTERP3],
    OFFICE: [OFFICEP1, OFFICEP2, OFFICEP3],
    FITNESS: [FITNESSP1, FITNESSP2, FITNESSP3],
    COUNSELING: [COUNSELINGP1, COUNSELINGP2, COUNSELINGP3]
};